DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NROMATRICULA INT NOT NULL, NOMBRE VARCHAR(60) NOT NULL, APELLIDO VARCHAR(60) NOT NULL);

-- requisito de la consigna --

INSERT INTO ODONTOLOGOS(NROMATRICULA, NOMBRE, APELLIDO) VALUES (12345, 'Juan', 'Perez'), (54321, 'Maria', 'Gomez');